module.exports = {
  Emily: {
    studentName: "Emily",
    parentName: "BillyBob joe",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "America/New_York",
  },
  Gray: {
    studentName: "Gray Powell",
    parentName: "BillyBob joe",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "America/New_York",
  },
  Katie: {
    studentName: "Katie",
    parentName: "BillyBob joe",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "America/New_York",
  },
  Paul: {
    studentName: "Paul Foreman",
    parentName: "BillyBob joe",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "Asia/Baku",
  },
  Camm: {
    studentName: "Camm",
    parentName: "Wendy",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "Asia/Baku",
  },
  Lauren: {
    studentName: "Lauren",
    parentName: "BillyBob joe",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "America/Chicago",
  },
  Lily: {
    studentName: "Lily",
    parentName: "BillyBob joe",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "America/Chicago",
  },
  Phoebe: {
    studentName: "Phoebe",
    parentName: "Amy Jaggers",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "Asia/Baku",
  },
  Ally: {
    studentName: "Ally sapire",
    parentName: "Courtney Freedman",
    studentNumber: 5122348292,
    parentNumber: 1123123123,
    studentEmail: "emily@gmail.com",
    parentEmail: "caroline@gmail.com",
    timeZone: "Asia/Baku",
  },
};
